{{- $name := include "blob-consumer.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "{{ $name }}-secret"
  labels:
    {{- include "blob-consumer.labels" . | nindent 4 }}
data:
  AzureWebJobsStorage:  {{ <storage-account-connection-string> | b64enc }}
  TEST_STORAGE_CONNECTION_STRING: {{ <blob-processing-storage-account-connection-string> | b64enc }}
